### Affine Functions with 1 Feature

### Affine Function

In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

x = tf.constant([[10.]])
print(x.shape)

dense = Dense(units=1, activation='linear') # input의 shape 을 모르는 상태기 때문에 init이 안됨
# W, B = dense.get_weights() 여기선 에러 발생!

Y_tf = dense(x) # Forward propagation + param 초기화 발생

W, B = dense.get_weights()

y_man = tf.linalg.matmul(x, W) + B # Forward propagation(manual)

print('===Input/Weight/Bias===')
print(f'x: {x.shape}/{x.numpy()}')
print(f'W: {W.shape}/{W}')
print(f'B: {B.shape}/{x}')

print('===Output===')
print(f'y TF: {Y_tf.shape} {Y_tf.numpy()}')
print(f'y Manumal: {y_man.shape} {y_man.numpy()}')

(1, 1)
===Input/Weight/Bias===
x: (1, 1)/[[10.]]
W: (1, 1)/[[-0.2556126]]
B: (1,)/[[10.]]
===Output===
y TF: (1, 1) [[-2.556126]]
y Manumal: (1, 1) [[-2.556126]]


### Params Initialization

In [2]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import Constant

w, b = tf.constant(10.), tf.constant(20.)
w_init, b_init = Constant(w), Constant(b)
print(w_init, b_init)

# initialize
dense = Dense(units=1,
            activation='linear',
            kernel_initializer=w_init,
            bias_initializer=b_init)

x = tf.constant([[10.]])
y_tf = dense(x)
W, B = dense.get_weights()

# result
print(f'W: {W.shape}/{W}')
print(f'B: {B.shape}/{x}')
print(y_tf)

<tensorflow.python.keras.initializers.initializers_v2.Constant object at 0x00000236C859C0A0> <tensorflow.python.keras.initializers.initializers_v2.Constant object at 0x00000236C859C070>
W: (1, 1)/[[10.]]
B: (1,)/[[10.]]
tf.Tensor([[120.]], shape=(1, 1), dtype=float32)


### Affine Functions with n Features

In [3]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

x = tf.random.uniform(shape=(1, 10), minval=0, maxval=10)
print(x.shape, x)

dense = Dense(units=1)
y_tf = dense(x)
w, b = dense.get_weights()
y_man = tf.linalg.matmul(x, w)

print(y_tf)
print(y_man)
print(w.shape, w)
print(b.shape, b)

(1, 10) tf.Tensor(
[[7.310574   8.756303   7.284135   0.73001266 5.1256123  7.1595583
  1.0547972  0.8894384  3.8202906  5.63066   ]], shape=(1, 10), dtype=float32)
tf.Tensor([[-4.03018]], shape=(1, 1), dtype=float32)
tf.Tensor([[-4.03018]], shape=(1, 1), dtype=float32)
(10, 1) [[-0.32732445]
 [-0.5919069 ]
 [-0.04982662]
 [ 0.6631437 ]
 [-0.20929849]
 [ 0.47903138]
 [-0.33477366]
 [ 0.34889752]
 [-0.01416683]
 [ 0.20682347]]
(1,) [0.]


### Activation Functions

### Activation Layers

In [4]:
import tensorflow as tf
from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation

x = tf.random.normal(shape=(1, 5))
sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

# forward propagation(tf)
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

# forward propagation(manual)
y_sigmoid_man = 1 / (1 + exp(-x))
y_tanh_man = (exp(x) - exp(-x)) / (exp(x) + exp(-x))
y_relu_man = maximum(x, 0)

print(f'x: {x.shape}\n{x}')
print(f'Sigmoid(TF): {y_sigmoid_tf}\n{y_sigmoid_tf.shape}')
print(f'Sigmoid(manual): {y_sigmoid_man}\n{y_sigmoid_man.shape}')

print(f'Tanh(TF): {y_tanh_tf}\n{y_tanh_tf.shape}')
print(f'Tanh(manual): {y_tanh_man}\n{y_tanh_man.shape}')

print(f'ReLU(TF): {y_relu_tf}\n{y_relu_tf.shape}')
print(f'ReLU(manual): {y_relu_man}\n{y_relu_man.shape}')

x: (1, 5)
[[ 0.30315638  0.6130659   1.1631515   0.44874308 -0.15970373]]
Sigmoid(TF): [[0.5752139  0.6486399  0.7619049  0.61034036 0.46015868]]
(1, 5)
Sigmoid(manual): [[0.5752139  0.6486399  0.7619049  0.61034036 0.46015868]]
(1, 5)
Tanh(TF): [[ 0.29419845  0.5462817   0.82206434  0.42086527 -0.15835966]]
(1, 5)
Tanh(manual): [[ 0.29419845  0.5462817   0.8220643   0.42086524 -0.15835968]]
(1, 5)
ReLU(TF): [[0.30315638 0.6130659  1.1631515  0.44874308 0.        ]]
(1, 5)
ReLU(manual): [[0.30315638 0.6130659  1.1631515  0.44874308 0.        ]]
(1, 5)


### Activation in Dense Layer

In [5]:
import tensorflow as tf
from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Dense

x = tf.random.normal(shape=(1, 5)) 

dense_sigmoid = Dense(units=1, activation='sigmoid')
dense_tanh = Dense(units=1, activation='tanh')
dense_relu = Dense(units=1, activation='relu')

# forward propagtaion
y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

print(f'AN with Sigmoid {y_sigmoid.shape}\n{y_sigmoid}')
print(f'AN with Tanh {y_tanh.shape}\n{y_tanh}')
print(f'AN with ReLU {y_relu.shape}\n{y_relu}')

print('==========')
w, b = dense_sigmoid.get_weights()
z = tf.linalg.matmul(x, w) + b
a = 1 / (1 + exp(-z))
print(f'atviation manual forward : {a.shape}\n{a}')

AN with Sigmoid (1, 1)
[[0.5059813]]
AN with Tanh (1, 1)
[[-0.98368865]]
AN with ReLU (1, 1)
[[0.78368676]]
atviation manual forward : (1, 1)
[[0.5059813]]


### Artificial Neurons 

In [6]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.math import exp, maximum

activation = 'sigmoid'

x = tf.random.uniform(shape=(1, 10))

dense = Dense(units=1, activation=activation)

y_tf = dense(x)
w, b = dense.get_weights()

y_man = tf.linalg.matmul(x, w) + b

if activation == 'sigmoid':
    y_man = 1 / (1 + exp(-y_man))
elif activation == 'tanh':
    y_man = (exp(y_man) - exp(-y_man)) / (exp(y_man) + exp(-y_man))
elif activation == 'relu':
    y_man = maximum(y_man, 0)

print("Activation :", activation)
print(f'y_tf: {y_tf.shape}\n{y_tf}')
print(f'y_man: {y_man.shape}\n{y_man}')

Activation : sigmoid
y_tf: (1, 1)
[[0.5110764]]
y_man: (1, 1)
[[0.5110764]]


### Minibatches

### Shape of Dense Layers

In [7]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_features = 8, 10
x = tf.random.normal(shape=(N, n_features))

dense = Dense(units=1, activation='relu')
y = dense(x)
w, b = dense.get_weights()
print(f'Shape of x : {x.shape}')
print(f'Shape of W : {w.shape}')
print(f'Shape of N : {b.shape}')



Shape of x : (8, 10)
Shape of W : (10, 1)
Shape of N : (1,)


### Output Calculations

In [8]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_features = 8, 10
x = tf.random.normal(shape=(N, n_features))

dense = Dense(units=1, activation='sigmoid')
y_tf = dense(x)

w, b = dense.get_weights()

y_man = tf.linalg.matmul(x, w) + b
y_man = 1 / (1 + tf.math.exp(-y_man))

print(f'Output of TF: \n {y_tf}')
print(f'Output of Manual: \n {y_man}')

Output of TF: 
 [[0.20659985]
 [0.94612145]
 [0.07187063]
 [0.80417866]
 [0.9185698 ]
 [0.19960007]
 [0.39711988]
 [0.09214338]]
Output of Manual: 
 [[0.20659985]
 [0.94612145]
 [0.07187063]
 [0.80417866]
 [0.9185698 ]
 [0.19960007]
 [0.39711988]
 [0.09214338]]
