### Dense Layers

### Shapes of Dense Layers

In [2]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feautre = 8, 10
X = tf.random.normal(shape=(N, n_feautre))

n_neuron = 3

dense = Dense(units=n_neuron, activation='sigmoid')
Y = dense(X)

W, B = dense.get_weights()
print('=== input/weight/bias ===')
print("x: ", X.shape)
print("w: ", W.shape)
print("b: ", B.shape)
print("y: ", Y.shape)


=== input/weight/bias ===
x:  (8, 10)
w:  (10, 3)
b:  (3,)
y:  (8, 3)


### Output Calculations

In [9]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.math import exp
from tensorflow.linalg import matmul
import numpy as np



N, n_feautre = 4, 10
X = tf.random.normal(shape=(N, n_feautre))

n_neuron = 3

dense = Dense(units=n_neuron, activation='sigmoid')
Y = dense(X)

W, B = dense.get_weights()
print('=== input/weight/bias ===')
print("y(tf): \n", Y.numpy())

# matmul
z = matmul(X, W) + B
y_man_matmul = 1 / (1 + exp(-z))
print("y(manual): \n", Y.numpy())

# dot products
y_man_vec = np.zeros(shape=(N, n_neuron))
for x_idx in range(N):
    x = X[x_idx]
    for nu_idx in range(n_neuron):
        w, b = W[:, nu_idx], B[nu_idx]

        z = tf.reduce_sum(x * w) + b
        a = 1 / (1 + np.exp(-z))
        y_man_vec[x_idx, nu_idx] = a

print("y(dot product): \n", y_man_vec)

=== input/weight/bias ===
y(tf): 
 [[0.66051465 0.48175505 0.59102505]
 [0.6642394  0.8516737  0.40843207]
 [0.9202743  0.4687363  0.3644462 ]
 [0.62595665 0.46364754 0.07252796]]
y(manual): 
 [[0.66051465 0.48175505 0.59102505]
 [0.6642394  0.8516737  0.40843207]
 [0.9202743  0.4687363  0.3644462 ]
 [0.62595665 0.46364754 0.07252796]]
y(dot product): 
 [[0.66051465 0.48175508 0.59102509]
 [0.66423938 0.85167371 0.4084321 ]
 [0.92027433 0.4687363  0.36444619]
 [0.62595664 0.46364751 0.07252799]]


### Cascaded Dense Layer

In [11]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neuron = [3, 5]
dense1 = Dense(units=n_neuron[0], activation='sigmoid')
dense2 = Dense(units=n_neuron[1], activation='sigmoid')

# forward
A1 = dense1(X)
Y = dense2(A1)

W1, B1 = dense1.get_weights()
W2, B2 = dense2.get_weights()

print('X :', X.shape)
print('W1 :', W1.shape)
print('B1 :', B1.shape)
print('A1 :', A1.shape)

print('W2 :', W2.shape)
print('B2 :', B2.shape)
print('Y :', Y.shape)

X : (4, 10)
W1 : (10, 3)
B1 : (3,)
A1 : (4, 3)
W2 : (3, 5)
B2 : (5,)
Y : (4, 5)


### Dense Layers with list

In [16]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neuron = [10, 20, 30, 40, 50, 60, 70, 80]
dense_layers = []
for n in n_neuron:
    dense = Dense(units=n, activation='relu')
    dense_layers.append(dense)

for dense_idx, d in enumerate(dense_layers):
    X = d(X)
    print('After dense', dense_idx + 1)
    print(X.shape)
Y = X

After dense 1
(4, 10)
After dense 2
(4, 20)
After dense 3
(4, 30)
After dense 4
(4, 40)
After dense 5
(4, 50)
After dense 6
(4, 60)
After dense 7
(4, 70)
After dense 8
(4, 80)


### Output calculations

In [24]:
import tensorflow as tf
from tensorflow.math import exp
from tensorflow.linalg import matmul

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))
x_cp = tf.identity(X)

n_neuron = [3, 4, 5]
dense_layers = []
for n in n_neuron:
    dense = Dense(units=n, activation='sigmoid')
    dense_layers.append(dense)

# forward
print('Input: ', X.shape)
W, B = [], []
for dense_idx, d in enumerate(dense_layers):
    X = d(X)
    w, b = d.get_weights()
    W.append(w)
    B.append(b)

print("Y(TF)", X.numpy())

# manual forward
for layer_idx in range(len(n_neuron)):
    w, b = W[layer_idx], B[layer_idx]
    x_cp = matmul(x_cp, w) + b
    x_cp = 1 / (1 + exp(-x_cp))
print("Y(manual)", x_cp.numpy())

Input:  (4, 10)
Y(TF) [[0.5758754  0.44308335 0.55577695 0.43275854 0.40059185]
 [0.5762585  0.45153323 0.5318519  0.42211947 0.39154565]
 [0.57775456 0.44705185 0.5435034  0.42777175 0.39305246]
 [0.5804851  0.44424984 0.5521302  0.43567234 0.3954671 ]]
Y(manual) [[0.5758754  0.44308335 0.55577695 0.43275854 0.40059185]
 [0.5762585  0.45153323 0.5318519  0.42211947 0.39154565]
 [0.57775456 0.44705185 0.5435034  0.42777175 0.39305246]
 [0.5804851  0.44424984 0.5521302  0.43567234 0.3954671 ]]


### Model Implementation

### Model implemetnation with Sequential Method

In [25]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

n_neuron = [3, 4, 5, 6]
model = Sequential()
for n in n_neuron:
    model.add(Dense(units=n, activation='sigmoid'))

### Model implementation with Model-subclassing

In [26]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model

class TestModel(Model):
    def __init__(self, *args, **kwargs):
        super(TestModel, self).__init__(*args, **kwargs)

        self.dense1 = Dense(units=10, activation='sigmoid')
        self.dense2 = Dense(units=20, activation='sigmoid')

model = TestModel()

### Forward Propagation of Models

In [31]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.models import Model

X = tf.random.normal(shape=(4, 10))
# sequential method
n_neuron = [3, 4, 5, 6]
model = Sequential()
for n in n_neuron:
    model.add(Dense(units=n, activation='sigmoid'))

Y = model(X)
print(Y.numpy())

class TestModel(Model):
    def __init__(self, *args, **kwargs):
        super(TestModel, self).__init__(*args, **kwargs)

        self.dense1 = Dense(units=3, activation='sigmoid')
        self.dense2 = Dense(units=6, activation='sigmoid')

    def call(self, x):
        x = self.dense1(x)
        x = self.dense2(x)
        return x

model = TestModel()
Y = model(Y)
print(Y.numpy())

[[0.42644915 0.3634584  0.42794952 0.32661465 0.66594714 0.31790614]
 [0.42750964 0.3643052  0.42573494 0.3345477  0.66118264 0.31678864]
 [0.42694992 0.36386877 0.42540056 0.32524517 0.66636854 0.3159413 ]
 [0.42672676 0.36595505 0.42883816 0.32874793 0.66418254 0.3185828 ]]
[[0.5438799  0.3161276  0.29188898 0.567872   0.5539243  0.5278989 ]
 [0.543958   0.31621492 0.29207432 0.56794804 0.5537214  0.5279601 ]
 [0.5438548  0.31625828 0.29204252 0.5678336  0.55386174 0.52788585]
 [0.54395974 0.31606734 0.29182774 0.5678598  0.5539599  0.52790785]]


### Layers in Models

In [37]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

X = tf.random.normal(shape=(4, 10))
# sequential method
n_neuron = [3, 4]
model = Sequential()
for n in n_neuron:
    model.add(Dense(units=n, activation='sigmoid'))

print(type(model.layers))
print(model.layers)
dense1 = model.layers[0]
print(dense1)

<class 'list'>
[<tensorflow.python.keras.layers.core.Dense object at 0x00000182A503EDC0>, <tensorflow.python.keras.layers.core.Dense object at 0x00000182A6EA2490>]


### Trainable Variables in Model

In [43]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

X = tf.random.normal(shape=(4, 10))
# sequential method
n_neuron = [3, 4]
model = Sequential()
for n in n_neuron:
    model.add(Dense(units=n, activation='sigmoid'))
y = model(X)

print(type(model.trainable_variables))
print(len(model.trainable_variables))
for train_var in model.trainable_variables:
    print(train_var.shape) # weights, bias

<class 'list'>
4
(10, 3)
(3,)
(3, 4)
(4,)
